"use strict";
exports.__esModule = true;
var env_config_1 = require("./env.config");
var app_1 = require("./app");
var logger_helper_1 = require("./helpers/logger.helper");
var env = process.env.NODE_ENV || 'Dev';
var envConfig = env_config_1.EnvConfig.getInstance();
envConfig.init(env);
var logger = logger_helper_1.Logger.getInstance();
logger.init(env);
var app = new app_1.App();
